# Training configuration parameters

num_episodes: 1000            # Number of episodes to train for
batch_size: 64                # Batch size for experience replay
max_steps_per_episode: 1000   # Maximum number of steps per episode
log_dir: "logs/"              # Directory to store training logs (for TensorBoard)
checkpoint_dir: "checkpoints/" # Directory to save model checkpoints
save_checkpoint_interval: 100  # Save model checkpoint every N episodes
